# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx6g
      # TYPESENSE_HOST: typesense.acdh-dev.oeaw.ac.at
      # TYPESENSE_PORT: 443
      # TYPESENSE_PROTOCOL: https
      # TYPESENSE_API_KEY: ${{secrets.TYPESENSE_API_KEY}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python and Dependencies
        run: |
          sudo apt-get update && sudo apt-get install python3 python3-pip openjdk-11-jre-headless ant -y
          pip install -r requirements.txt

      - name: Run Custom Shell Script
        run: ./shellscripts/script.sh

      - name: Fetch the Data
        run: |
          echo "Fetching data..."
          ./fetch_data.sh

      - name: Build the App
        run: |
          echo "Building the app..."
          ant || { echo 'Ant build failed'; exit 1; }

      - name: Check HTML Directory
        run: if [ ! -d "./html" ]; then echo "HTML directory not found!"; exit 1; fi

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Create htpasswd File
        run: htpasswd -b -c .htpasswd admin "${{ env.IMAGE_NAME }}"
